main/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('prediction_page/', views.main, name='prediction_page'),
    
    path('main/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]

testdrive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/models.py
from django.db import models


class PredResults2(models.Model):
    id = models.AutoField(primary_key=True)
    area = models.FloatField()
    Fertilizers = models.FloatField()
    Rainfall = models.FloatField()
    Storage = models.FloatField()
    Electricity = models.FloatField()
    yeild = models.FloatField()
    prices = models.FloatField()

    def __str__(self):
        return self.id

main/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults2
import numpy as np
from numpy.linalg import inv

def main(request):
    return render(request, 'main.html')


def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        area = float(request.POST.get('area'))
        Fertilizers = float(request.POST.get('Fertilizers'))
        Rainfall = float(request.POST.get('Rainfall'))
        Storage = float(request.POST.get('Storage'))
        Electricity = float(request.POST.get('Electricity'))
       # yeild = float(request.POST.get('yeild'))



        data = pd.read_csv('E:\python\YT-Django-Iris-App-3xj9B0qqps-master - Copy\predict\MVRprices1.csv') 
        colums = (data.columns[0])
        #finding minimum and maximum fom each column
        max= [data[c].max() for c in data.columns] 
        min= [data[c].min() for c in data.columns]
        i=0
        #print(max,min)
        #normalizing the data
        for c in data.columns:
            while(i<len(data.columns)): 
              data[c]=(data[c]-min[i])/(max[i]-min[i])
              i=i+1
              break
        #print(data)
        arr = data.values
        #print(arr)
        #Now, split the dataset and store the features and target values in different list. Here, I have stored the features in x_train list and the target values in y1.
        x_train=[]
        y1=[]
        a=data.shape
        for i in range(a[0]):                      
            x_train.append((arr[i][:-1]).tolist())
    
            y1.append(arr[i][-1])
        #Concatenate the x_train list with matrix of 1ˢ and compute the coefficient matrix using the normal equation . numpy built-in functions for matrix operations.
        #Input the test data and thereby store it in a list, x_test. Predict the target variable using the test data and the coefficient matrix and thereby stored the result in Y1
        m=np.ones((12,1))
        b=np.matrix(x_train)
        b=np.concatenate((m,b),axis=1)     
        d=b.T#transpose
        e=np.linalg.inv(np.matmul(d,b))#inverse
        y1=np.matrix(y1)
        y1=y1.T
        f=np.matmul(e,d)
        c1=np.matmul(f,y1)
        x_test=[[1],]
        inp=[area,Fertilizers,Rainfall,Storage,Electricity]
        print(inp,x_test)
        for j in range (5):
            
            x_test.append([inp[j]])
        
        print(x_test)

        for i in range(5):
            x_test[i+1][0]=(x_test[i+1][0]-min[i])/(max[i]-min[i])
        x_test=np.matrix(x_test)
        Y1=np.matmul(c1.T,x_test)

        print(Y1*(max[-1]-min[-1])+min[-1])
        k= Y1*(max[-1]-min[-1])+min[-1]
        #area,Fertilizers,Rainfall,Storage,Electricity,yeild,Prices
        # Unpickle model
        #model = pd.read_pickle(r"E:\python\YT-Django-Iris-App-3xj9B0qqps-master\new_model.pickle")
        # Make prediction
       # result = model.predict([[area,Fertilizers,Rainfall,Storage,Electricity,yeild]])

        yeild = float(k)
        print(float(k))

        
        data1 = pd.read_csv('E:\python\YT-Django-Iris-App-3xj9B0qqps-master - Copy\predict\MVRprices.csv') 
        colums1 = (data1.columns[0])
        #finding minimum and maximum fom each column
        max= [data1[c].max() for c in data1.columns] 
        min= [data1[c].min() for c in data1.columns]
        i=0
        #print(max,min)
        #normalizing the data
        for c in data1.columns:
            while(i<len(data1.columns)): 
              data1[c]=(data1[c]-min[i])/(max[i]-min[i])
              i=i+1
              break
        #print(data)
        arr1 = data1.values
        #print(arr)
        #Now, split the dataset and store the features and target values in different list. Here, I have stored the features in x_train list and the target values in y1.
        x_train1=[]
        y11=[]
        a1=data1.shape
        for i in range(a1[0]):                      
            x_train1.append((arr1[i][:-1]).tolist())
    
            y11.append(arr1[i][-1])
        #Concatenate the x_train list with matrix of 1ˢ and compute the coefficient matrix using the normal equation . numpy built-in functions for matrix operations.
        #Input the test data and thereby store it in a list, x_test. Predict the target variable using the test data and the coefficient matrix and thereby stored the result in Y1
        m1=np.ones((12,1))
        b1=np.matrix(x_train1)
        b1=np.concatenate((m1,b1),axis=1)     
        d1=b1.T#transpose
        e1=np.linalg.inv(np.matmul(d1,b1))#inverse
        y11=np.matrix(y11)
        y11=y11.T
        f1=np.matmul(e1,d1)
        c11=np.matmul(f1,y11)
        x_test1=[[1],]
        inp1=[area,Fertilizers,Rainfall,Storage,Electricity,yeild]
        print(inp1,x_test1)
        for j in range (6):
            
            x_test1.append([inp1[j]])
        
        print(x_test1)

        for i in range(6):
            x_test1[i+1][0]=(x_test1[i+1][0]-min[i])/(max[i]-min[i])
        x_test1=np.matrix(x_test1)
        Y11=np.matmul(c11.T,x_test1)

        print(Y11*(max[-1]-min[-1])+min[-1])
        k1= Y11*(max[-1]-min[-1])+min[-1]
        #area,Fertilizers,Rainfall,Storage,Electricity,yeild,Prices
        # Unpickle model
        #model = pd.read_pickle(r"E:\python\YT-Django-Iris-App-3xj9B0qqps-master\new_model.pickle")
        # Make prediction
       # result = model.predict([[area,Fertilizers,Rainfall,Storage,Electricity,yeild]])

        prices = float(k1)
        print(float(k1))

        PredResults2.objects.create(area=area,Fertilizers=Fertilizers,Rainfall=Rainfall,Storage=Storage,Electricity=Electricity,yeild=yeild, prices=prices)

        return JsonResponse({'prices': prices,'area' : area,'Fertilizers' : Fertilizers,'Rainfall' : Rainfall, 'Storage' : Storage,'Electricity' : Electricity, 'yeild': yeild },
                            safe=False)

def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults2.objects.all()}
    return render(request, "results.html", data)
def index (request): 
    return render(request, 'index.html')

main/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>AgriPrediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/main">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

main/templates/main.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>area: <span id="a"></span></div>
                <div>Fertilizers: <span id="f"></span></div>
                <div>Rainfall: <span id="r"></span></div>
                <div>Storage: <span id="s"></span></div>
                <div>Electricity: <span id="e"></span></div>
           
                <h5 class="pt-3">Prediction:</h5>
               
                prices:<div id="prices"></div>
                yeild:<div id="yeild"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
             
                <div class="form-group">
                    <label for="area">area</label>
                    <input type="number" step="0.1" class="form-control" id="area" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Fertilizers">Fertilizers</label>
                    <input type="number" step="0.1" class="form-control" id="Fertilizers" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Rainfall">Rainfall</label>
                    <input type="number" step="0.1" class="form-control" id="Rainfall" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Storage">Storage</label>
                    <input type="number" step="0.1" class="form-control" id="Storage" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Electricity">Electricity</label>
                    <input type="number" step="0.1" class="form-control" id="Electricity" placeholder="" required>
                </div>
   
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "main:submit_prediction" %}',
            
            data:{
                area:$('#area').val(),
                Fertilizers:$('#Fertilizers').val(),
                Rainfall:$('#Rainfall').val(),
                Storage:$('#Storage').val(),
                Electricity:$('#Electricity').val(),
              

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prices").innerHTML = json['prices']
                document.getElementById("yeild").innerHTML = json['yeild']
                document.getElementById("a").innerHTML = json['area']
                document.getElementById("f").innerHTML = json['Fertilizers']
                document.getElementById("r").innerHTML = json['Rainfall']
                document.getElementById("s").innerHTML = json['Storage']
                document.getElementById("e").innerHTML = json['Electricity']
                
                
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

main/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                    
                <th scope="col">#</th>
                <th scope="col">a</th>
                <th scope="col">f</th>
                <th scope="col">r</th>
                <th scope="col">s</th>
                <th scope="col">e</th>
                <th scope="col">y</th>
                <th scope="col">p</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                   
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.area }}</td>
                    <td>{{ data.Fertilizers }}</td>
                    <td>{{ data.Rainfall }}</td>
                    <td>{{ data.Storage }}</td>
                    <td>{{ data.Electricity }}</td>
                    <td>{{ data.yeild }}</td>
                    <td>{{ data.prices }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>AgriPrediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/main">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>